name: Actions workflow_call
on: [push]
jobs:
  run-github-action:
    runs-on: ubuntu-latest
    steps: 
      - name: List Files
        run: |
          pwd
          ls
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@main
        with:
          who-to-greet: 'Mona the Octocat'
      - name: Log Greeting Time
        run: echo "${{steps.greet.outputs.time}}"